-- Snowflake Permissions Setup
-- Grant necessary permissions to roles

USE DATABASE TRANSIT_DB;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE TRANSIT_WH TO ROLE TRANSIT_ROLE;
GRANT OPERATE ON WAREHOUSE TRANSIT_WH TO ROLE TRANSIT_ROLE;

-- Grant database usage
GRANT USAGE ON DATABASE TRANSIT_DB TO ROLE TRANSIT_ROLE;
GRANT USAGE ON DATABASE TRANSIT_DB TO ROLE TRANSIT_INGESTION_ROLE;

-- Grant schema usage
GRANT USAGE ON SCHEMA RAW TO ROLE TRANSIT_INGESTION_ROLE;
GRANT USAGE ON SCHEMA STAGING TO ROLE TRANSIT_ROLE;
GRANT USAGE ON SCHEMA MARTS TO ROLE TRANSIT_ROLE;
GRANT USAGE ON SCHEMA ML TO ROLE TRANSIT_ROLE;

-- Grant table permissions
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE TRANSIT_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA RAW TO ROLE TRANSIT_INGESTION_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE TRANSIT_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA RAW TO ROLE TRANSIT_INGESTION_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAGING TO ROLE TRANSIT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STAGING TO ROLE TRANSIT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MARTS TO ROLE TRANSIT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MARTS TO ROLE TRANSIT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ML TO ROLE TRANSIT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ML TO ROLE TRANSIT_ROLE;

-- Grant pipe permissions
GRANT OWNERSHIP ON PIPE TRANSIT_RAW_PIPE TO ROLE TRANSIT_INGESTION_ROLE;
GRANT OWNERSHIP ON PIPE GTFS_ROUTES_PIPE TO ROLE TRANSIT_INGESTION_ROLE;
GRANT OWNERSHIP ON PIPE GTFS_STOPS_PIPE TO ROLE TRANSIT_INGESTION_ROLE;

