{{
  config(
    materialized='table',
    schema='ML',
    tags=['ml_forecasts', 'demand', 'snowflake_ml']
  )
}}

{#
  ML Forecast: Demand Forecast using Snowflake ML FORECAST
  
  Uses CREATE SNOWFLAKE.ML.FORECAST to create and train a forecasting model,
  then uses the model to predict future demand.
  
  Source: stg_gtfs_stop_times, stg_gtfs_trips, stg_gtfs_routes
#}

-- Step 1: Prepare historical data for forecasting
WITH trip_routes AS (
    SELECT DISTINCT
        t.trip_id,
        tr.route_id,
        r.route_short_name,
        r.agency
    FROM {{ ref('stg_gtfs_stop_times') }} t
    LEFT JOIN {{ ref('stg_gtfs_trips') }} tr ON t.trip_id = tr.trip_id
    LEFT JOIN {{ ref('stg_gtfs_routes') }} r ON tr.route_id = r.route_id
    WHERE tr.route_id IS NOT NULL
),

historical_data AS (
    SELECT 
        tr.route_id,
        tr.route_short_name,
        tr.agency,
        DATE(t.loaded_at) as ts,
        COUNT(*) as departure_count
    FROM {{ ref('stg_gtfs_stop_times') }} t
    LEFT JOIN trip_routes tr ON t.trip_id = tr.trip_id
    WHERE t.loaded_at >= DATEADD(day, -90, CURRENT_DATE())
        AND tr.route_id IS NOT NULL
    GROUP BY tr.route_id, tr.route_short_name, tr.agency, DATE(t.loaded_at)
    ORDER BY tr.route_id, ts
),

-- Step 2: Create and train forecast model for each route
forecast_models AS (
    SELECT DISTINCT
        route_id,
        route_short_name,
        agency
    FROM historical_data
),

-- Step 3: Generate forecasts using Snowflake ML FORECAST
-- Note: This requires creating the model first via DDL, then calling FORECAST method
-- For dbt, we'll create a macro or use a Python model to handle this

forecast_results AS (
    SELECT 
        route_id,
        route_short_name,
        agency,
        ts as forecast_date,
        departure_count as predicted_departures,
        CURRENT_TIMESTAMP() as forecast_generated_at
    FROM historical_data
    WHERE ts >= CURRENT_DATE()
    LIMIT 0  -- Placeholder - actual forecast will be generated by Python model
)

SELECT * FROM forecast_results

-- IMPORTANT: Actual Snowflake ML FORECAST implementation requires:
-- 1. CREATE SNOWFLAKE.ML.FORECAST model_name FROM (SELECT ts, value FROM historical_data)
-- 2. CALL model_name!FORECAST(FORECASTING_PERIODS => 7)
-- 
-- This should be done in a Python dbt model or Airflow DAG that:
-- - Creates the forecast model for each route
-- - Trains the model
-- - Generates forecasts
-- - Stores results in ML.DEMAND_FORECAST table

