AWSTemplateFormatVersion: '2010-09-09'
Description: 'Transit Service Reliability & Demand Planning System - AWS Infrastructure'

Parameters:
  TransitAppAPIKey:
    Type: String
    Description: TransitApp API Key (will be stored in Secrets Manager)
    NoEcho: true
  SnowflakeAccount:
    Type: String
    Description: Snowflake account identifier (e.g., xy12345.us-west-2)
  SnowflakeUser:
    Type: String
    Description: Snowflake user for integration
  SnowflakePassword:
    Type: String
    Description: Snowflake password (will be stored in Secrets Manager)
    NoEcho: true
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # =============================================================================
  # S3 BUCKETS
  # =============================================================================
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'transit-raw-data-${AWS::AccountId}-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: MoveToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
          - Id: DeleteOldVersions
            Status: Enabled
            ExpirationInDays: 365
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt SnowpipeNotificationQueue.Arn

  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'transit-processed-${AWS::AccountId}-${Environment}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'transit-artifacts-${AWS::AccountId}-${Environment}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # =============================================================================
  # SQS QUEUES
  # =============================================================================
  IngestionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'transit-ingestion-queue-${Environment}'
      VisibilityTimeoutSeconds: 300
      MessageRetentionPeriod: 1209600  # 14 days
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'transit-ingestion-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days

  # SQS Queue for Snowpipe notifications
  SnowpipeNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'transit-snowpipe-notifications-${Environment}'
      VisibilityTimeoutSeconds: 300
      MessageRetentionPeriod: 1209600

  # =============================================================================
  # IAM ROLES
  # =============================================================================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'transit-lambda-execution-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TransitLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                Resource:
                  - !Sub '${RawDataBucket}/*'
                  - !Sub '${ProcessedDataBucket}/*'
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource:
                  - !GetAtt IngestionQueue.Arn
                  - !GetAtt DeadLetterQueue.Arn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref TransitAppAPIKeySecret

  # IAM Role for Snowflake to access S3
  SnowflakeS3IntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'transit-snowflake-s3-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub '${AWS::AccountId}-${Environment}'
      Policies:
        - PolicyName: SnowflakeS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub '${RawDataBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource: !Ref RawDataBucket

  # =============================================================================
  # SECRETS MANAGER
  # =============================================================================
  TransitAppAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'transit/transitapp-api-key-${Environment}'
      Description: TransitApp API Key
      SecretString: !Ref TransitAppAPIKey

  SnowflakeCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'transit/snowflake-credentials-${Environment}'
      Description: Snowflake credentials
      SecretString: !Sub |
        {
          "account": "${SnowflakeAccount}",
          "user": "${SnowflakeUser}",
          "password": "${SnowflakePassword}"
        }

  # =============================================================================
  # LAMBDA FUNCTIONS
  # =============================================================================
  TransitAPIIngestionFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'transit-api-ingestion-${Environment}'
      Runtime: python3.9
      Handler: transit_api_ingestion.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          TRANSIT_APP_API_KEY_SECRET: !Ref TransitAppAPIKeySecret
          RAW_DATA_BUCKET: !Ref RawDataBucket
          INGESTION_QUEUE_URL: !Ref IngestionQueue
          AWS_REGION: !Ref AWS::Region
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          # Placeholder - will be replaced with actual code during deployment
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Placeholder')}

  GTFSSyncFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'transit-gtfs-sync-${Environment}'
      Runtime: python3.9
      Handler: gtfs_sync.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          RAW_DATA_BUCKET: !Ref RawDataBucket
          AWS_REGION: !Ref AWS::Region
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          # Placeholder - will be replaced with actual code during deployment
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Placeholder')}

  # =============================================================================
  # EVENTBRIDGE RULES (SCHEDULES)
  # =============================================================================
  TransitAPIIngestionSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'transit-api-ingestion-schedule-${Environment}'
      Description: Trigger TransitApp API ingestion every 5 minutes
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt TransitAPIIngestionFunction.Arn
          Id: TransitAPIIngestionTarget

  GTFSSyncSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'transit-gtfs-sync-schedule-${Environment}'
      Description: Sync GTFS feeds daily at 2 AM UTC
      ScheduleExpression: cron(0 2 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt GTFSSyncFunction.Arn
          Id: GTFSSyncTarget

  # =============================================================================
  # LAMBDA PERMISSIONS
  # =============================================================================
  TransitAPIIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TransitAPIIngestionFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt TransitAPIIngestionSchedule.Arn

  GTFSSyncPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GTFSSyncFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt GTFSSyncSchedule.Arn

  # =============================================================================
  # CLOUDWATCH ALARMS
  # =============================================================================
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'transit-lambda-errors-${Environment}'
      AlarmDescription: Alert when Lambda errors exceed threshold
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300  # 5 minutes
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref TransitAPIIngestionFunction
      AlarmActions:
        - !Ref ErrorNotificationTopic

  SQSQueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'transit-sqs-queue-depth-${Environment}'
      AlarmDescription: Alert when SQS queue depth exceeds threshold
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt IngestionQueue.QueueName
      AlarmActions:
        - !Ref ErrorNotificationTopic

  S3BucketSizeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'transit-s3-bucket-size-${Environment}'
      AlarmDescription: Alert when S3 bucket size exceeds 10GB
      MetricName: BucketSizeBytes
      Namespace: AWS/S3
      Statistic: Average
      Period: 86400  # Daily
      EvaluationPeriods: 1
      Threshold: 10737418240  # 10GB in bytes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref RawDataBucket
        - Name: StorageType
          Value: StandardStorage
      AlarmActions:
        - !Ref ErrorNotificationTopic

  # =============================================================================
  # SNS TOPIC FOR ALERTS
  # =============================================================================
  ErrorNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'transit-error-notifications-${Environment}'
      DisplayName: Transit System Error Notifications

Outputs:
  RawDataBucketName:
    Description: Name of the S3 bucket for raw data
    Value: !Ref RawDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-RawDataBucket'

  RawDataBucketArn:
    Description: ARN of the raw data S3 bucket
    Value: !GetAtt RawDataBucket.Arn

  SnowflakeS3RoleArn:
    Description: ARN of the IAM role for Snowflake S3 integration
    Value: !GetAtt SnowflakeS3IntegrationRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SnowflakeS3Role'

  SnowpipeNotificationQueueArn:
    Description: ARN of SQS queue for Snowpipe notifications
    Value: !GetAtt SnowpipeNotificationQueue.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SnowpipeNotificationQueue'

  IngestionQueueUrl:
    Description: URL of the ingestion SQS queue
    Value: !Ref IngestionQueue
    Export:
      Name: !Sub '${AWS::StackName}-IngestionQueue'

  TransitAPIIngestionFunctionArn:
    Description: ARN of the TransitApp API ingestion Lambda function
    Value: !GetAtt TransitAPIIngestionFunction.Arn

  GTFSSyncFunctionArn:
    Description: ARN of the GTFS sync Lambda function
    Value: !GetAtt GTFSSyncFunction.Arn

