version: 2

sources:
  - name: landing
    description: Landing tables from GTFS and streaming data
    database: "{{ target.database }}"
    schema: "LANDING"
    tables:
      - name: landing_gtfs_stops
        description: GTFS stops from landing layer
      - name: landing_gtfs_routes
        description: GTFS routes from landing layer
      - name: landing_gtfs_trips
        description: GTFS trips from landing layer
      - name: landing_gtfs_stop_times
        description: GTFS stop times from landing layer
      - name: landing_streaming_departures
        description: Streaming departures from Kafka

  - name: raw
    description: Raw tables (legacy/placeholder)
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    tables:
      - name: transit_stops
        description: Transit stops (placeholder)
      - name: transit_departures
        description: Transit departures (placeholder)
      - name: transit_alerts
        description: Transit alerts (placeholder)
